/*
 * Login.java
 *
 * Created on __DATE__, __TIME__
 */

package com.kiiik.quotes;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;

import javax.management.JMException;

import org.apache.log4j.Logger;
import org.quickfixj.jmx.JmxExporter;

import quickfix.ConfigError;
import quickfix.DefaultMessageFactory;
import quickfix.FileStoreFactory;
import quickfix.Initiator;
import quickfix.LogFactory;
import quickfix.MessageFactory;
import quickfix.MessageStoreFactory;
import quickfix.ScreenLogFactory;
import quickfix.SessionSettings;
import quickfix.SocketInitiator;

/**
 * 停止使用  2015年6月1日 14:38:59   使用handler.intTradeClientApp()代替 
 * 在linux上使用异常，windows上可以正常使用。
 * 功能描述：
 * 作者：iechenyb
 * 创建时间：2015年6月1日下午2:38:52
 */
public class ExchangeLogin extends javax.swing.JFrame {
	protected final transient Logger log = Logger.getLogger(ExchangeLogin.class);
	public Initiator initiator = null;
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	/** Creates new form Login */
	public ExchangeLogin() {
		System.out.println("ExchangeLogin.initComponents....");
		initComponents();
		System.out.println("ExchangeLogin.initComponents over....");
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		System.out.println("ExchangeLogin. inner initComponents....");
		btnOk = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtUserAccount = new javax.swing.JTextField();
		pdUserPassword = new javax.swing.JPasswordField();
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		btnOk.setText("\u767b\u5f55");
		btnOk.setName("btnName");
		btnOk.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				System.out.println("entering to the click  event...");
				jButton1ActionPerformed(evt);
			}
		});
		btnOk.doClick();
		jLabel1.setText("\u8d26\u53f7");

		jLabel2.setText("\u5bc6\u7801");

		txtUserAccount.setText("70108228");
		txtUserAccount.setName("txtUserAccount");

		pdUserPassword.setText("987654");
		pdUserPassword.setName("pdUserPassword");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				153,
																				153,
																				153)
																		.addComponent(
																				btnOk))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				57,
																				57,
																				57)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel1)
																						.addComponent(
																								jLabel2))
																		.addGap(
																				86,
																				86,
																				86)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								pdUserPassword,
																								0,
																								0,
																								Short.MAX_VALUE)
																						.addComponent(
																								txtUserAccount,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								101,
																								Short.MAX_VALUE))))
										.addContainerGap(132, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGap(24, 24, 24)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																txtUserAccount,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												33, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																pdUserPassword,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(22, 22, 22).addComponent(
												btnOk).addGap(36, 36, 36)));

		btnOk.getAccessibleContext().setAccessibleName("btnName");
		txtUserAccount.getAccessibleContext().setAccessibleName("txtUserAccount");
		pdUserPassword.getAccessibleContext().setAccessibleName(
				"pdUserPassword");

		pack();
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		this.setVisible(false);
		System.out.println("init intTradeClientApp start....");
		intTradeClientApp();
		System.out.println("init intTradeClientApp end....");
	}

	 TradeClientApp intTradeClientApp() {
		try {
			System.out.println("init intTradeClientApp 1111....");
			String settingPath = Contants.settingPath;;
			File file = new File(settingPath+File.separator+"tradeclient.cfg");
			InputStream inputStream = new FileInputStream(file);
			SessionSettings settings = new SessionSettings(inputStream);
			//将配置文件里的三个路径重新写入，因为路径问题，2015年5月28日 14:44:26 add by iechenyb
			String FileStorePath = settingPath+File.separator+"tradeclient";
			String TransportDataDictionary = settingPath+File.separator+"FIXT.1.1.xml";
			String AppDataDictionary = settingPath+File.separator+"FIX50SP2.xml";
			settings.setString("FileStorePath", FileStorePath);
			settings.setString("TransportDataDictionary", TransportDataDictionary);
			settings.setString("AppDataDictionary", AppDataDictionary);
			inputStream.close();
			System.out.println("init intTradeClientApp 2222....");
			TradeClientApp tradeClientApp = new TradeClientApp();
			tradeClientApp.userName   ="";
			tradeClientApp.password   ="";
			tradeClientApp.version   ="version";
			MessageStoreFactory messageStoreFactory = new FileStoreFactory(settings);
			System.out.println("init intTradeClientApp 3333....");
			LogFactory logFactory = new ScreenLogFactory(settings);
			System.out.println("init intTradeClientApp 4444....");
			MessageFactory messageFactory = new DefaultMessageFactory();
			System.out.println("init intTradeClientApp 5555....");
			log.info("SocketInitiator start...");
			initiator = new SocketInitiator(tradeClientApp, messageStoreFactory
						, settings, logFactory, messageFactory);
			System.out.println("init intTradeClientApp 6666....");
			initiator.start();
			System.out.println("init intTradeClientApp 7777....");
			log.info("SocketInitiator end...");
			JmxExporter exporter = new JmxExporter();
			System.out.println("init intTradeClientApp 8888....");
			exporter.register(initiator);
			System.out.println("init intTradeClientApp 9999....");
			log.info("exporter.register(initiator) end");
			return tradeClientApp;
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (ConfigError e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		} catch (JMException e) {
			e.printStackTrace();
		}
		return null;
	}
	
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				ExchangeLogin login  = new ExchangeLogin();
				login.setVisible(false);
			}
		});
	}

	private javax.swing.JButton btnOk;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPasswordField pdUserPassword;
	private javax.swing.JTextField txtUserAccount;

}